/**
 * @Generated by sagacity-quickvo 4.16
 */
package com.sqltoy.quickstart.vo;

import com.sqltoy.quickstart.vo.base.AbstractCgformFtlVO;
import org.sagacity.sqltoy.config.annotation.SqlToyEntity;

/**
 * @project sqltoy-quickstart
 * @author S5
 * @version 1.0.0
 * Table: cgform_ftl 	
 */
@SqlToyEntity
public class CgformFtlVO extends AbstractCgformFtlVO {

  /**
   *
   */
  private static final long serialVersionUID = 4350922581323967073L;

  /** default constructor */
  public CgformFtlVO() {
    super();
  }

  /*---begin-constructor-area---don't-update-this-area--*/

  /** pk constructor */
  public CgformFtlVO(String id) {
    this.id = id;
  }

  /*---end-constructor-area---don't-update-this-area--*/

  /**
   * @todo vo columns to String
   */
  @Override
  public String toString() {
    return super.toString();
  }

  /*
   * (non-Javadoc)
   *
   * @see java.lang.Object#clone()
   */
  @Override
  public CgformFtlVO clone() {
    try {
      return (CgformFtlVO) super.clone();
    } catch (CloneNotSupportedException e) {
      e.printStackTrace();
    }
    return null;
  }

}
